export enum ShipmentStatus {
  DELIVERED_TO_SENDER = "DELIVERED_TO_SENDER",
  OUT_FOR_DELIVERY='OUT_FOR_DELIVERY',
  NOT_YET_SHIPPED='NOT_YET_SHIPPED',
  PACKAGE_RECEIVED='PACKAGE_RECEIVED',
  DELIVERED='DELIVERED',
  CANCELLED='CANCELLED'
}
